on:
  push:
    branches: ["main"]

name: Deploy Next.js site to IONOS

jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: nextjs-site
    
      - name: Deploy to IONOS via SFTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: access794949688.webspace-data.io
          port: 22
          username: u98282221
          password: IUbf29guufU98&/
          local-dir: ./out/
