name: Deploy Next.js site to IONOS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build with Next.js
        run: npm run build
      
      - name: Static HTML export with Next.js
        run: npm run export
      
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v2
        with:
          name: nextjs-site
          path: ./VINKOM/out

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: nextjs-site
    
      - name: Deploy to IONOS via SFTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: sftp://access794949688.webspace-data.io
          port: 22
          username: u98282221
          password: IUbf29guufU98&/
          local-dir: ./VINKOM/out/
